daysUntilStale: 14
daysUntilClose: 1
exemptLabels:
  - blocked
  - bug
  - documentation
  - enhancement
  - task
  - invalid
staleLabel: invalid
markComment: >
  This issue has been automatically marked as `invalid` because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false
