version: "{build}"
image: Visual Studio 2017

environment:
  matrix:
    - JAVA_HOME: C:/Program Files/Java/jdk1.8.0

before_build:
  - mvnw.cmd clean install -B -V -DskipTests

build_script:
  - mvnw.cmd clean install

on_failure:
  - ps: |
      7z a -r surefire-reports.zip '**\target\surefire-reports\*'
      Push-AppveyorArtifact surefire-reports.zip -DeploymentName 'Surefire Reports'

cache:
  - C:/Users/appveyor/.m2
